# Obtiene las completaciones del editor basadas en el esquema de configuraciÃ³n
# "$schema" = 'https://starship.rs/config-schema.json'

# Inserta una lÃ­nea en blanco entre los prompts del intÃ©rprete de comandos
add_newline = true

# Reemplaza el sÃ­mbolo "â¯" en el prompt por "âœ"
[character] # El nombre del mÃ³dulo que estamos configurando es "character"
success_symbol = "[â¯ ](bold green)" # El segmento "success_symbol" se estÃ¡ oonfigurando es "âœ" con el color "bold green"

# Deshabilita el mÃ³dulo "package", ocultÃ¡ndolo del prompt completamente
[package]
disabled = true

# ~/.config/starship.toml

[nodejs]
format = "[ğŸ¤– node $version](bold green)"
symbol = "ğŸ¤–"

[git_branch]
symbol = "ğŸŒ± "